//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWMS.WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLWMS.WinForms.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobro nam došli.
        /// </summary>
        public static string DobroDosli {
            get {
                return ResourceManager.GetString("DobroDosli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija.
        /// </summary>
        public static string Informacija {
            get {
                return ResourceManager.GetString("Informacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaš korisnički nalog nije aktivan.
        /// </summary>
        public static string NalogNijeAktivan {
            get {
                return ResourceManager.GetString("NalogNijeAktivan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ove vrijednosti je obavezan.
        /// </summary>
        public static string ObaveznaVrijednost {
            get {
                return ResourceManager.GetString("ObaveznaVrijednost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni podaci nisu validni.
        /// </summary>
        public static string PodaciNisuValidni {
            get {
                return ResourceManager.GetString("PodaciNisuValidni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci uspješno dodati u bazu.
        /// </summary>
        public static string PodaciUspjesnoDodati {
            get {
                return ResourceManager.GetString("PodaciUspjesnoDodati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci uspjenso modifikovani.
        /// </summary>
        public static string PodaciUspjesnoModifikovani {
            get {
                return ResourceManager.GetString("PodaciUspjesnoModifikovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatak {0} je već dodat.
        /// </summary>
        public static string PodatakVecPostoji {
            get {
                return ResourceManager.GetString("PodatakVecPostoji", resourceCulture);
            }
        }
    }
}
